/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Game = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Text,
  'isHome' : IDL.Bool,
  'homeScore' : IDL.Opt(IDL.Nat),
  'awayScore' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
  'opponent' : IDL.Text,
});
export const NewsPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'assists' : IDL.Nat,
  'goals' : IDL.Nat,
  'playerNumber' : IDL.Nat,
});
export const Player = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'maxPrepsUrl' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'hometown' : IDL.Text,
  'number' : IDL.Nat,
  'eliteProspectsUrl' : IDL.Opt(IDL.Text),
  'photo' : IDL.Text,
  'position' : IDL.Text,
});
export const TeamInfo = IDL.Record({
  'leaguePosition' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'overtimeLosses' : IDL.Nat,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addGame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'addNewsPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPlayer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCompletedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getLatestNews' : IDL.Func([IDL.Nat], [IDL.Vec(NewsPost)], ['query']),
  'getNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getPlayerStats' : IDL.Func([], [IDL.Vec(PlayerStats)], ['query']),
  'getPlayerStatsByNumber' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PlayerStats)],
      ['query'],
    ),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getTeamInfo' : IDL.Func([], [TeamInfo], ['query']),
  'getUpcomingGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'removeGame' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeNewsPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removePlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setPlayerStats' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateGameScores' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'updateNewsPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePlayer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateTeamInfo' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Text,
    'isHome' : IDL.Bool,
    'homeScore' : IDL.Opt(IDL.Nat),
    'awayScore' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
    'opponent' : IDL.Text,
  });
  const NewsPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
  });
  const PlayerStats = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'assists' : IDL.Nat,
    'goals' : IDL.Nat,
    'playerNumber' : IDL.Nat,
  });
  const Player = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'maxPrepsUrl' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'hometown' : IDL.Text,
    'number' : IDL.Nat,
    'eliteProspectsUrl' : IDL.Opt(IDL.Text),
    'photo' : IDL.Text,
    'position' : IDL.Text,
  });
  const TeamInfo = IDL.Record({
    'leaguePosition' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'overtimeLosses' : IDL.Nat,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    'addGame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'addNewsPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCompletedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getLatestNews' : IDL.Func([IDL.Nat], [IDL.Vec(NewsPost)], ['query']),
    'getNewsPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getPlayerStats' : IDL.Func([], [IDL.Vec(PlayerStats)], ['query']),
    'getPlayerStatsByNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerStats)],
        ['query'],
      ),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getTeamInfo' : IDL.Func([], [TeamInfo], ['query']),
    'getUpcomingGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'removeGame' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeNewsPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removePlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setPlayerStats' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateGameScores' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'updateNewsPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePlayer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateTeamInfo' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };