/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : bigint,
  'isCompleted' : boolean,
  'date' : string,
  'isHome' : boolean,
  'homeScore' : [] | [bigint],
  'awayScore' : [] | [bigint],
  'location' : string,
  'opponent' : string,
}
export interface NewsPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'date' : string,
}
export interface Player {
  'age' : bigint,
  'weight' : string,
  'height' : string,
  'maxPrepsUrl' : [] | [string],
  'name' : string,
  'hometown' : string,
  'number' : bigint,
  'eliteProspectsUrl' : [] | [string],
  'photo' : string,
  'position' : string,
}
export interface PlayerStats {
  'gamesPlayed' : bigint,
  'assists' : bigint,
  'goals' : bigint,
  'playerNumber' : bigint,
}
export interface TeamInfo {
  'leaguePosition' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'overtimeLosses' : bigint,
  'points' : bigint,
}
export interface _SERVICE {
  'addGame' : ActorMethod<[string, string, string, boolean, string], undefined>,
  'addNewsPost' : ActorMethod<[string, string, string, string], undefined>,
  'addPlayer' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'changePassword' : ActorMethod<[string, string], undefined>,
  'getCompletedGames' : ActorMethod<[], Array<Game>>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getLatestNews' : ActorMethod<[bigint], Array<NewsPost>>,
  'getNewsPosts' : ActorMethod<[], Array<NewsPost>>,
  'getPlayerStats' : ActorMethod<[], Array<PlayerStats>>,
  'getPlayerStatsByNumber' : ActorMethod<[bigint], [] | [PlayerStats]>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'getTeamInfo' : ActorMethod<[], TeamInfo>,
  'getUpcomingGames' : ActorMethod<[], Array<Game>>,
  'removeGame' : ActorMethod<[bigint, string], undefined>,
  'removeNewsPost' : ActorMethod<[bigint, string], undefined>,
  'removePlayer' : ActorMethod<[bigint, string], undefined>,
  'setPlayerStats' : ActorMethod<
    [bigint, bigint, bigint, bigint, string],
    undefined
  >,
  'updateGameScores' : ActorMethod<
    [bigint, bigint, bigint, boolean, string],
    undefined
  >,
  'updateNewsPost' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updatePlayer' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'updateTeamInfo' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];