/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    age: bigint;
    weight: string;
    height: string;
    maxPrepsUrl?: string;
    name: string;
    hometown: string;
    number: bigint;
    eliteProspectsUrl?: string;
    photo: string;
    position: string;
}
export interface Game {
    id: bigint;
    isCompleted: boolean;
    date: string;
    isHome: boolean;
    homeScore?: bigint;
    awayScore?: bigint;
    location: string;
    opponent: string;
}
export interface TeamInfo {
    leaguePosition: bigint;
    wins: bigint;
    losses: bigint;
    overtimeLosses: bigint;
    points: bigint;
}
export interface PlayerStats {
    gamesPlayed: bigint;
    assists: bigint;
    goals: bigint;
    playerNumber: bigint;
}
export interface NewsPost {
    id: bigint;
    title: string;
    body: string;
    date: string;
}
export interface backendInterface {
    addGame(date: string, opponent: string, location: string, isHome: boolean, password: string): Promise<void>;
    addNewsPost(title: string, body: string, date: string, password: string): Promise<void>;
    addPlayer(number: bigint, name: string, position: string, photo: string, height: string, weight: string, age: bigint, hometown: string, maxPrepsUrl: string | null, eliteProspectsUrl: string | null, password: string): Promise<void>;
    changePassword(oldPassword: string, newPassword: string): Promise<void>;
    getCompletedGames(): Promise<Array<Game>>;
    getGames(): Promise<Array<Game>>;
    getLatestNews(count: bigint): Promise<Array<NewsPost>>;
    getNewsPosts(): Promise<Array<NewsPost>>;
    getPlayerStats(): Promise<Array<PlayerStats>>;
    getPlayerStatsByNumber(playerNumber: bigint): Promise<PlayerStats | null>;
    getPlayers(): Promise<Array<Player>>;
    getTeamInfo(): Promise<TeamInfo>;
    getUpcomingGames(): Promise<Array<Game>>;
    removeGame(id: bigint, password: string): Promise<void>;
    removeNewsPost(id: bigint, password: string): Promise<void>;
    removePlayer(number: bigint, password: string): Promise<void>;
    setPlayerStats(playerNumber: bigint, goals: bigint, assists: bigint, gamesPlayed: bigint, password: string): Promise<void>;
    updateGameScores(id: bigint, homeScore: bigint, awayScore: bigint, isCompleted: boolean, password: string): Promise<void>;
    updateNewsPost(id: bigint, title: string, body: string, date: string, password: string): Promise<void>;
    updatePlayer(number: bigint, name: string, position: string, photo: string, height: string, weight: string, age: bigint, hometown: string, maxPrepsUrl: string | null, eliteProspectsUrl: string | null, password: string): Promise<void>;
    updateTeamInfo(wins: bigint, losses: bigint, overtimeLosses: bigint, points: bigint, leaguePosition: bigint, password: string): Promise<void>;
}
import type { Game as _Game, Player as _Player, PlayerStats as _PlayerStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGame(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGame(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGame(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addNewsPost(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsPost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsPost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPlayer(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: string | null, arg9: string | null, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
    async changePassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1);
            return result;
        }
    }
    async getCompletedGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedGames();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedGames();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGames();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGames();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestNews(arg0: bigint): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestNews(arg0);
            return result;
        }
    }
    async getNewsPosts(): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPosts();
            return result;
        }
    }
    async getPlayerStats(): Promise<Array<PlayerStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStats();
            return result;
        }
    }
    async getPlayerStatsByNumber(arg0: bigint): Promise<PlayerStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStatsByNumber(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStatsByNumber(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamInfo(): Promise<TeamInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamInfo();
            return result;
        }
    }
    async getUpcomingGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingGames();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingGames();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeGame(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGame(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGame(arg0, arg1);
            return result;
        }
    }
    async removeNewsPost(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNewsPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNewsPost(arg0, arg1);
            return result;
        }
    }
    async removePlayer(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayer(arg0, arg1);
            return result;
        }
    }
    async setPlayerStats(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlayerStats(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlayerStats(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateGameScores(arg0: bigint, arg1: bigint, arg2: bigint, arg3: boolean, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameScores(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameScores(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateNewsPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsPost(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsPost(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePlayer(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: string | null, arg9: string | null, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
    async updateTeamInfo(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamInfo(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamInfo(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_Game_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerStats]): PlayerStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isCompleted: boolean;
    date: string;
    isHome: boolean;
    homeScore: [] | [bigint];
    awayScore: [] | [bigint];
    location: string;
    opponent: string;
}): {
    id: bigint;
    isCompleted: boolean;
    date: string;
    isHome: boolean;
    homeScore?: bigint;
    awayScore?: bigint;
    location: string;
    opponent: string;
} {
    return {
        id: value.id,
        isCompleted: value.isCompleted,
        date: value.date,
        isHome: value.isHome,
        homeScore: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.homeScore)),
        awayScore: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.awayScore)),
        location: value.location,
        opponent: value.opponent
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: string;
    height: string;
    maxPrepsUrl: [] | [string];
    name: string;
    hometown: string;
    number: bigint;
    eliteProspectsUrl: [] | [string];
    photo: string;
    position: string;
}): {
    age: bigint;
    weight: string;
    height: string;
    maxPrepsUrl?: string;
    name: string;
    hometown: string;
    number: bigint;
    eliteProspectsUrl?: string;
    photo: string;
    position: string;
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        maxPrepsUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.maxPrepsUrl)),
        name: value.name,
        hometown: value.hometown,
        number: value.number,
        eliteProspectsUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.eliteProspectsUrl)),
        photo: value.photo,
        position: value.position
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n8(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
